import Head from 'next/head'
import { useRouter } from 'next/router'
import Header from '@components/Header/Header'
import SkeletonManagement from '@components/Management/Layout/Layout'
import SkeletonParentSystem from '@components/ParentSystem/Layout/Layout'

import '@styles/globals.css'
import '@styles/fonts.css'
export default function({ Component, pageProps }) {
  const router = useRouter();
  const routerPath = router.pathname.split('/').filter(Boolean);

  let body = <Component { ...pageProps } />;
  if (routerPath?.[0] === 'management') {
    body = (
      <SkeletonManagement>
        { body }
      </SkeletonManagement>
    );
  }
  if (routerPath?.[0] === 'parentSystem') {
    body = (
      <SkeletonParentSystem>
        { body }
      </SkeletonParentSystem>
    );
  }

  return (
    <div>
      <Head>
        <title>오일러EDU</title>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="theme-color" content="#ffffff" />
        { /* for test */ }
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="apple-touch-icon" href="/eulerLogo/logo192.png" />
        <link rel="manifest" href="/manifest.json" />
        <script
          type="text/javascript"
          src={ `//dapi.kakao.com/v2/maps/sdk.js?appkey=${ process.env.kakaoApiKey }&libraries=services,clusterer` }
        />
      </Head>
      <Header />
      { body }
    </div>
  )
}
