import Head from 'next/head'
import Header from '@components/Header/Header'

import '@styles/globals.css'

export default function({ Component, pageProps }) {
  return (
    <div>
      <Head>
        <title>오일러EDU</title>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="theme-color" content="#ffffff" />
        { /* for test */ }
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="apple-touch-icon" href="/eulerLogo/logo192.png" />
        <link rel="manifest" href="/manifest.json" />
        { /* for test */ }
        <link href="https://hangeul.pstatic.net/hangeul_static/css/nanum-barun-gothic.css" rel="stylesheet" />
      </Head>
      <Header />
      <Component { ...pageProps } />
    </div>
  )
}
